name          'hadenlabs-xvfb'
version       'v1.0.0'
source        ''
author        'luis mayta'
license       'Mit'
summary       ''
description   ''
project_page  'https://github.com/hadenlabs/puppet-module-xvfb'

dependency 'puppetlabs/stdlib'
